# This is a workflow to test and deploy our demo app.

name: ColdBrew CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DEMO_HOME: /home/runner/work/coldbrew-coders/back-end
  PYTHONPATH: /home/runner/work/coldbrew-coders/coldbrew-coders:/home/runner/work/coldbrew-coders/coldbrew-coders/server:/home/runner/work/coldbrew-coders/coldbrew-coders/server/db
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # environment: heroku-deploy

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install Python packages.
        run: pip install -r requirements-dev.txt

      - name: Run Python tests.
        working-directory: ./back-end
        run: make all_tests

      # Deploy to Heroku
      #  - uses: akhileshns/heroku-deploy@v3.12.12
      #    with:
      #        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #        heroku_app_name: "demo-repo3"
      #        heroku_email: "ejc369@nyu.edu"
