# This is a workflow to test and deploy our demo app.

name: ColdBrew CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DEMO_HOME: /home/runner/work/coldbrew-coders/back-end
  PYTHONPATH: /home/runner/work/coldbrew-coders/coldbrew-coders:/home/runner/work/coldbrew-coders/coldbrew-coders/server:/home/runner/work/coldbrew-coders/coldbrew-coders/server/db
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: 'Create env file'
        run: |
          touch .env
          echo connection_string="mongodb+srv://cold_brewer2023:fVWumO0TGmoj1JaZ@cluster0.wux8g.mongodb.net/?retryWrites=true&w=majority" >> .env
          echo local_connect_string="mongodb://0.0.0.0:27017/" >> .env
          echo CLOUD_MONGO="1" >> .env
          echo LOCAL_MONGO="0" >> .env
          cat .env
      
      - name: Install Python packages.
        run: pip install -r requirements-dev.txt

      - name: Run Python tests.
        run: make all_tests

      - name: Deploy to api server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
          REMOTE_HOST: ${{secrets.HOST_DNS}}
          REMOTE_USER: ${{secrets.USERNAME}}
          TARGET: ${{secrets.TARGET_DIR}}

      - name: Deploy to start lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ec2_start
          source: lambda/ec2_start.py

      - name: Deploy to stop lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ec2_stop
          source: lambda/ec2_stop.py

    - name: Invoke ec2_start Lambda
      uses: gagoar/invoke-aws-lambda@master
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        FunctionName: ec2_start
        # Payload: '{ "myParameter": false }'

      - name: Run server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST_DNS }}
          username: ${{secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export PATH=/home/ec2-user/.local/bin:$PATH
            export PYTHONPATH=/home/ec2-user/coldbrew-coders/server:$PYTHONPATH
            export PYTHONPATH=/home/ec2-user/coldbrew-coders/:$PYTHONPATH
            export PYTHONPATH=/home/ec2-user/coldbrew-coders/db:$PYTHONPATH

            cd ..
            cd ..
            cd home/ec2-user/coldbrew-coders/server
            nohup ./local.sh &
